#!/usr/bin/env bash
# A Bash script that stops the 4-to_infinity_and_beyond process
# WITHOUT using kill or killall

# Find PID of the process and send SIGTERM using `pkill` with -SIGTERM
pkill -f -SIGTERM 4-to_infinity_and_beyond
