#!/usr/bin/env bash
# Script that displays a message forever and handles SIGTERM gracefully

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
