#!/usr/bin/env bash
# List all non-hidden files; print part after dash if any

shopt -s nullglob

for file in *; do
  if [[ "$file" == *-* ]]; then
    echo "${file#*-}"
  else
    echo "$file"
  fi
done
