#!/usr/bin/env bash
# List files, printing part after first dash if it exists; ignore hidden files

shopt -s nullglob

for file in *; do
  if [[ "$file" == *-* ]]; then
    echo "${file#*-}"
  else
    echo "$file"
  fi
done
